version: "3.7"

services:

  flask:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"

  vue:
    build: .
    container_name: frontend
    restart: always
    ports:
      - "80:80"
